### ISSUE TITLE
Please add support to xregexp 4.4.0

### ISSUE THREAD

**Issue by sachithd** [ddycai/chord-transposer#14]
The library fails after updating the xregexp version to 4.4.0. (Works fine on 4.2.4). Thanks

**Comment by davidfabreguette** [comment]
Yep ! 
Getting this error with "4.4.0" :
```
"export 'exec' (imported as 'XRegExp') was not found in 'xregexp'
```

For those struggling with yarn like me, I had to force resolution for "chord-transposer" package like that in my package.json file :
```
"resolutions": {
    "chord-transposer/xregexp": "4.3.0"
  },
```

**Comment by ddycai** [comment]
I updated the dependency to 4.4.0 and the tests passed. I'm not sure why it was broken for you after updating. Let me know if it works now.
