### ISSUE TITLE
Sharp Key Signatures

### ISSUE THREAD

**Issue by nwestfall** [ddycai/chord-transposer#8]
More a question that could lead to a PR.  Why in `KeySignatures` is there only support for flats?

For example, I have a song in the key of `C#`, but the only way I can transpose is to say it's `Db`.  This, however, will make some of the chords technically incorrect by making them `Cb` instead of `B`.

Is it an issue to add support for more sharps in `KeySignatures`?  I'll gladly create the PR if so 👍

**Comment by ddycai** [comment]
You're right that here is currently no support for enharmonically equivalent key signatures. There wasn't a specific reason for this other than it made it easier to implement. Feel free to make a PR if you have an idea for its implementation!
